### ISSUE TITLE
Interested in contributing

### ISSUE THREAD

**Issue by jayschwa** [chsc/gogl#23]
Christoph, I am interested in helping you further develop and evolve this package. I like the things you have here: https://github.com/chsc/GoGL/wiki/Further-development-ideas

I would e-mail you to start discussion, but I can't find your address anywhere! If you wish, you can get back to me here: jay at jayschwa dot net

**Comment by jayschwa** [comment]
In the meantime, I guess I will add some random thoughts and questions here. After reading "further dev ideas" in the wiki, my main questions are:

## Questions
1. Is the package's API breakable? Your idea to replace GL types with Go types seems to indicate that you're willing to break compatibility with the existing API. My opinion is that this is acceptable if it means a better package in the long run. However, I'm not already relying heavily on the current API... some other people might be though :pensive:
2. Is the package supposed to be a 1:1 mirror of the GL C API, or would you like it to become something that resembles an idiomatic Go package? Or both? Perhaps there can be two packages: a "raw" package that is a 1:1 mirror of the GL C API, and an "idiomatic" package that wraps the "raw" one and makes it very "Go"-like.

## More idiomatic design?

The following are some thoughts on what could be done to make the package feel more idiomatic.

### Stricter types

The wiki page suggests replacing GL types with Go types. I suggest taking it one step further and creating specific types: Buffer, Program, Shader, etc.

Rather than taking or returning generic Uints, the functions will require or return a specific type. Example:

``` Go
type Program Uint
type Shader Uint

func CreateProgram() Program
func CreateShader() Shader
func AttachShader(prog Program, shad Shader)
```

### Errors via return

Currently, you have to call `GetError()` or whatever after virtually every call if you want to be thorough. Obviously, the Go way is to return an error with the call. I have created a prototype branch of this: https://github.com/jayschwa/gogl/tree/errors

Of course, it breaks API compatibility though :frowning:.

### Maximum idiom

Off the top of my head, this is an example of what a "fully idiomatic" API might look like:

``` Go
type Shader struct {
    Ref    gl.Uint
    Source string
    Type   gl.Enum
}

func CreateShader(type gl.Enum) (*Shader, error)
func (shader *Shader) Compile() error
func (shader *Shader) Delete() error
func (shader *Shader) Log() (string, error)

func NewShader(type gl.Enum, src string) (*Shader, error) {
    // Pretend error-checking is done
    shader := CreateShader(type)
    shader.Source = src
    shader.Compile()
    return shader, nil
}

type Program struct {
    Ref     gl.Uint
    Shaders []Shader
}

func CreateProgram() (*Program, error)
func (prog *Program) Delete() error
func (prog *Program) Attach(shader Shader) error
func (prog *Program) Detach(shader Shader) error
func (prog *Program) Link() error
func (prog *Program) Log() (string, error)

func NewProgram(shaders []Shader) (*Program, error) {
    // Pretend error-checking and is done
    prog := CreateProgram()
    for _, shader := range shaders {
        prog.Attach(shader)
    }
    prog.Link()
    return prog, nil
}

// Function name sucks, but you get the idea
func NewFooProgram(vertex, geometry, fragment string) (*Program, error) {
    // Pretend error-checking is done
    vert := NewShader(gl.VERTEX_SHADER, vertex)
    geom := NewShader(gl.GEOMETRY_SHADER, geometry)
    frag := NewShader(gl.FRAGMENT_SHADER, fragment)
    return NewProgram([]Shader{vert, geom, frag})
}
```

### Additional utilities

I love the idea of being able to go from a Go image.Image to a GL texture.

**Comment by metaleap** [comment]
Might I chime in... I have chosen GoGL over the other Go-OpenGL binding precisely because of the minimum amount of superfluous / additional Go code it adds. The generated binding is as raw and "minimalist" (in terms of added fancies) as possible, I like that. Other bindings go on the path of "let's be more idiomatic" and devolve into all kinds of wrappers and utilities and what not. I'd rather roll those myself with full awareness of any performance implications, than having any black-box automagic intermixed in the same package with pure required binding-related cgo code.

If anything were to be added to gogl that's pure Go code on top of the current generated "raw Cgo" sources, then at a minimum I'd ask you guys to create a separate optional package for such goodies, plz  ;)

**You might also be interested in my own take at some light minimalist wrappers&utils for GoGL:** ~~http://github.com/go3d/go-glutil/~~ http://github.com/go3d/go-opengl/util (update, no longer based on GoGL) -- especially with regards to your "Shader" and "Program" struct samples above -- check out program.go shader.go and program-manager.go...

(Only caveat, the package considers GL 3.3 as the minimum base version. Newer-than-3.3 things are checked against the current GL context's version, but 3.3-or-older stuff is considered available. Also only considers GL functionality that is still valid and permissible in a strict core-profile context, although it doesn't require a core-profile context.)

Just to stress -- the "raw Cgo and nothing else" philosophy of GoGL generated bindings is a major feature for some developers out there. This is a big bonus really.

This is also good for beginners to learn the "original OpenGL ways" like a C coder would. One can always look for or roll their own little wrapper frameworks later on. But it's always good to have available a zero-overhead, zero-baggage native direct immediate raw interface  :))

**Comment by metaleap** [comment]
"I love the idea of being able to go from a Go image.Image to a GL texture."

Check out my SetFromImage() method in go-glutil/texture-2d.go ... it's not too tricky but incomplete yet. Not handling sRGB meta-data in images properly yet, for one. Then it would be smarter to create gl.RGB instead of gl.RGBA for images that don't have an A component to begin with (seems like image.Image just always uses A and just sets it to 1 by default? No clue, one of my many to-dos...)

"Replacing GoGL types with Go types":

not in favour. Using gl.Uint instead of uint32 for example actually helps me better understand my code semantically, it's actually easier to separate what stuff is supposed to end up at the GPU and what stays on the CPU, so to speak.

Regarding type casts -- I was under the impression if I have a declaration type Foo string and then have Foo(string) or string(Foo) conversions anywhere, the Go compiler should be smart enough to make this zero-cost? Will have to double-check that assumption...

"Currently, you have to call GetError() or whatever after virtually every call if you want to be thorough. Obviously, the Go way is to return an error with the call."

Actually there is a good case to be made for the current setup. That is, once we have a solid code that runs fine and loopingly produces frames many times per second, we don't actually want to issue many many gl.LastError() calls to the GPU driver per frame. I mean it all adds up in the driver's command buffer, effectively doubling the number of driver commands sent per frame if our binding were to automagically do it for every gl.SomeFunc() call. Number of calls in the GPU driver's command buffer can matter at some point. Once I'm sure I won't need it, it would just be a horrendous waste. Don't do that. IMHO, close-to-the-metal APIs such as OpenGL don't have to fit Go's idiomatic error handling.

Now I myself also DO have a fair number of places in my go-glutil package where I call gl.LastError() and return a Go err for it. But this is for stuff that is most-most-likely not being called every frame and could (even with rock-solid code) still "always go wrong" for various valid reasons that aren't self-inflicted coding bugs, such as BufferData()s, TexSubImage2D()s or shader compilations etc.

**Comment by jayschwa** [comment]
Most of your points are convincing. Thanks.

I think an idiomatic package should probably be on top of a 1:1 mirror package and not mixed. I'm just curious what Christoph has in mind after seeing some of his ideas on the wiki page.

**Comment by chsc** [comment]
Hi Jay,

thanks for your interest in contributing to GoGL.
Breaking APIs is always bad, so I don’t plan to do this. The idea of replacing GL types with Go types is just an idea. It has some pros and cons and I have already discussed them here: https://github.com/go-gl/gl/issues/51. But the more I think about it, the more I come to the conclusion that I’ll leave it in the current state. 100% type compatibility is more important than having native Go types.
GoGL is 1:1 mirror of OpenGL, so I don’t plan to add too much abstraction nonsense to it. OpenGL is mostly used in data visualization and games. Speed is more important than fancy API indirections, idiomatic type conversions or unnecessary additional error checking.
GoGL will always be “raw” and “pure”. There are only a few functions where I plan to add some handwritten utility functions. E.g. functions with strings and callbacks as parameters.

**Comment by jayschwa** [comment]
Thanks for the clarifications.
