### ISSUE TITLE
How to create an offset with Pointer

### ISSUE THREAD

**Issue by ghost** [chsc/gogl#3]
Hello,

I have a buffer structure which contains vertex and texture coordinates.
Within C I could use  glVertexAttribPointer(GLuint index,  GLint size,  GLenum type,  GLboolean normalized,  GLsizei stride,  const GLvoid \* pointer);  and pass for example a 8 as a pointer.
With Go I can't do gl.Pointer(8).
func VertexAttribPointer(index Uint, size Int, type_ Enum, normalized Boolean, stride Sizei, pointer Pointer)

How do you set an byte offset with the pointer value?

**Comment by Kalthorn** [comment]
I feel like this is a weird part of the GL spec that makes it confusing for anyone writing a port/wrapper.  I really have no idea why a simple integer byte offset parameter would need a pointer (talking about the C API here).  I've not looked at the source code for gogl but you could just edit it yourself so that AttribPointer takes a uintptr as the final parameter.  Then wrap that with an unsafe.Pointer for the C function.  This makes the interface from Go code much cleaner as you can just past any integer directly without having to do a conversion (and the parameter can have a friendly name like 'byteOffset' instead of 'pointer').

I'm not the most experienced OpenGL user in the world but I honestly don't know any time that an actual pointer is necessary so I changed the API to just take a uintptr for my private branch (which I should really share) of Banthar's Go-OpenGL package.  You can find my discussion about that here: https://github.com/banthar/Go-OpenGL/issues/44

**Comment by chsc** [comment]
I want to keep the binding as close as possible to the original OpenGL C spec. That's the reason why I translate every void\* to gl.Pointer. The last argument of VertexAttribPointer is not only an offset. It's only treated as an offset if a vertex buffer object is bound to a GL_ARRAY_BUFFER target. If no vertex array is bound to this target it's simply an address to the raw vertex data. The same for TexCoordPointer, NormalPointer, ... (See specification documents: http://www.opengl.org/sdk/docs/man/xhtml/glVertexAttribPointer.xml, http://www.opengl.org/sdk/docs/man/xhtml/glTexCoordPointer.xml, http://www.opengl.org/sdk/docs/man/xhtml/glNormalPointer.xml)

You could try this:

func Offset(p gl.Pointer, o uint) gl.Pointer {
   return gl.Pointer(uintptr(p) + uintptr(o))
}
...
// with vbo
gl.VertexAttribPointer(..., Offset(nil, 8))
...
// without vbo
gl.VertexAttribPointer(..., Offset(&vertexData[0], 8))

Let me know if this works and I'll add it as an utility function.

**Comment by ghost** [comment]
Thanks, the Offset function works.

**Comment by Kalthorn** [comment]
And thanks for the clarification regarding the parameter.
